In [178]:
import numpy as np

In [179]:
a= np.array([1,2,3,4],dtype=np.int32)
a

array([1, 2, 3, 4], dtype=int32)

In [180]:
b= np.array([[1,2,4],[5,6,7]])

In [181]:
b

array([[1, 2, 4],
       [5, 6, 7]])

In [182]:
b.ndim

2

In [183]:
b.shape

(2, 3)

In [184]:
b[-1,1]

np.int64(6)

In [185]:
c =np.array([[[1,2],[2,3],[4,5]],[[1,2],[11,24],[34,34]]])
c

array([[[ 1,  2],
        [ 2,  3],
        [ 4,  5]],

       [[ 1,  2],
        [11, 24],
        [34, 34]]])

In [186]:
d=np.zeros((2,4),dtype='int32')
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [187]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [188]:
np.random.rand(4,2)

array([[0.10464363, 0.0828968 ],
       [0.32803291, 0.66873777],
       [0.71562848, 0.6282627 ],
       [0.62080273, 0.12819196]])

In [189]:
np.random.randint(1,100,(3,3))

array([[39, 87, 79],
       [89, 67, 16],
       [93, 62, 78]], dtype=int32)

In [190]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [191]:
np.ones((1,2),dtype='int32')

array([[1, 1]], dtype=int32)

In [192]:
a = np.array([1,2,3,4])
a+=2
a

array([3, 4, 5, 6])

In [193]:
b = np.random.randint(1,100,(3,3))
print(b)
c=b*3
print(c)
c+=b
c

[[15 45 40]
 [73 43 53]
 [ 3 31 76]]
[[ 45 135 120]
 [219 129 159]
 [  9  93 228]]


array([[ 60, 180, 160],
       [292, 172, 212],
       [ 12, 124, 304]], dtype=int32)

In [194]:
x=np.full((3,3),3)
x

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [195]:
np.min(x)
x=np.random.randint(1,100,(3,3))
x

array([[30, 20, 78],
       [51, 11, 41],
       [12, 82, 15]], dtype=int32)

In [196]:
np.max(x,axis=0)

array([51, 82, 78], dtype=int32)

In [197]:
np.sum(x,axis=1)

array([128, 103, 109])