In [2]:
import numpy as np

In [3]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
a[1,5]

np.int64(13)

In [5]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [6]:
a[1,-1]

np.int64(14)

In [7]:
a[0,1:-1:2]

array([2, 4, 6])

In [8]:
a[1,-1]

np.int64(14)

In [10]:
a[1,-1]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 20]]


Different Types of arrays


In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])